### ISSUE TITLE
Azure AD connect

### ISSUE THREAD

**Issue by Soberraccon** [Microsoft/aad-hybrid-lab#3]
Sorry for posting this under issues but I wasn't sure where else to ask this.

Are you able to connect a local Active Directory with Azure Active Directory just using these scripts ? I need to automate the full install process of AzureADConnect.msi and this repository seems to be the closest thing I could find.
Thank you!

**Comment by cocallaw** [comment]
@bretthackermsft should be able to help answer this question

**Comment by Soberraccon** [comment]
Thank you for the reply.  
The project I am working on is in co-operation with Microsoft. It is just hard to find the people who know these exact details.

**Comment by bretthackermsft** [comment]
This script won't actually connect the AD to the AAD - all it does is pre-install Connect on the machine so it's ready to go. There's no way to automate the configuration of Connect via script.

If there's value in pre-installing Connect, the relevant script that's doing that is at https://github.com/Microsoft/aad-hybrid-lab/blob/master/aad-hybrid-lab/DSC/adDSC/adDSCConfiguration.ps1#L39.

**Comment by Soberraccon** [comment]
**Thank you very much for your time!** This confirmation is very helpful. I will still need to automate this process but now I can be more confident that there is no official functionality to do it at this time.

If possible, can you reference a person or department on Microsoft side who might be able to discuss a technical solution on how to automate this process?
